version: "3.9"
services:
  # Creates a genesis state for the beacon chain using a YAML configuration file and
  # a deterministic set of 64 validators.
  create-beacon-chain-genesis:
    container_name: genesis-creator
    # image: "gcr.io/prysmaticlabs/prysm/cmd/prysmctl:HEAD-ec954e"
    image: "gcr.io/prysmaticlabs/prysm/cmd/prysmctl:latest"
    command:
      - testnet
      - generate-genesis
      - --fork=capella
      - --num-validators=64
      #- --genesis-time-delay=15
      - --output-ssz=/consensus/genesis.ssz
      - --chain-config-file=/config/config.yml
      - --geth-genesis-json-in=/execution/genesis.json
      - --geth-genesis-json-out=/execution/genesis.json
    volumes:
      - ./consensus:/consensus
      - ./config:/config
      - ./execution:/execution

  # Removes the database of the go-ethereum execution client to ensure we start from a clean state.
  # (geth has a `removedb` option, but it asks for a keyboard confirmation, so we use this instead)
  geth-remove-db:
    container_name: geth-db-cleaner
    image: "alpine:3.19.0"
    command: rm -rf /execution/geth
    volumes:
      - ./execution:/execution

  # Sets up the genesis configuration for the go-ethereum client from a JSON file.
  geth-genesis:
    container_name: geth-genesis
    image: "ethereum/client-go:release-1.14"
    command: --datadir=/execution init /execution/genesis.json
    volumes:
      - ./execution:/execution
      - ./execution/genesis.json:/execution/genesis.json
    depends_on:
      create-beacon-chain-genesis:
        condition: service_completed_successfully
      geth-remove-db:
        condition: service_completed_successfully

  # Runs the go-ethereum execution client with the specified, unlocked account and necessary
  # APIs to allow for proof-of-stake consensus via Prysm.
  geth:
    container_name: geth-execution
    image: "ethereum/client-go:release-1.14"
    command: ${GETH_ARGS}
    depends_on:
      geth-genesis:
        condition: service_completed_successfully
    volumes:
      - ./execution:/execution

  # Runs a Prysm beacon chain from a specified genesis state created in the previous step
  # and connects to go-ethereum in the same network as the execution client.
  # The account used in go-ethereum is set as the suggested fee recipient for transactions
  # proposed via the validators attached to the beacon node.
  beacon-chain-1:
    container_name: beacon-1
    image: "gcr.io/prysmaticlabs/prysm/beacon-chain:latest"
    command: ${BEACON_CHAIN_1_ARGS}
    depends_on:
      geth:
        condition: service_started
      create-beacon-chain-genesis:
        condition: service_completed_successfully
    volumes:
      - ./consensus:/consensus
      - ./config:/config
      - ./execution:/execution

  beacon-chain-2:
    container_name: beacon-2
    image: "gcr.io/prysmaticlabs/prysm/beacon-chain:latest"
    command: ${BEACON_CHAIN_2_ARGS}
    depends_on:
      geth:
        condition: service_started
      create-beacon-chain-genesis:
        condition: service_completed_successfully
    volumes:
      - ./consensus:/consensus
      - ./config:/config
      - ./execution:/execution

  beacon-chain-3:
    container_name: beacon-3
    image: "gcr.io/prysmaticlabs/prysm/beacon-chain:latest"
    command: ${BEACON_CHAIN_3_ARGS}
    depends_on:
      geth:
        condition: service_started
      create-beacon-chain-genesis:
        condition: service_completed_successfully
    volumes:
      - ./consensus:/consensus
      - ./config:/config
      - ./execution:/execution

  beacon-chain-4:
    container_name: beacon-4
    image: "gcr.io/prysmaticlabs/prysm/beacon-chain:latest"
    command: ${BEACON_CHAIN_4_ARGS}
    depends_on:
      geth:
        condition: service_started
      create-beacon-chain-genesis:
        condition: service_completed_successfully
    volumes:
      - ./consensus:/consensus
      - ./config:/config
      - ./execution:/execution

  # We run a validator client with 64, deterministically-generated keys that match
  # The validator keys present in the beacon chain genesis state generated a few steps above.
  validator-1:
    container_name: validator-1
    image: "gcr.io/prysmaticlabs/prysm/validator:latest"
    command: ${VALIDATOR_1_ARGS}
    depends_on:
      beacon-chain-1:
        condition: service_started
    volumes:
      - ./consensus:/consensus
      - ./config:/config

  validator-2:
    container_name: validator-2
    image: "gcr.io/prysmaticlabs/prysm/validator:latest"
    command: ${VALIDATOR_2_ARGS}
    depends_on:
      beacon-chain-2:
        condition: service_started
    volumes:
      - ./consensus:/consensus
      - ./config:/config

  validator-3:
    container_name: validator-3
    image: "gcr.io/prysmaticlabs/prysm/validator:latest"
    command: ${VALIDATOR_3_ARGS}
    depends_on:
      beacon-chain-3:
        condition: service_started
    volumes:
      - ./consensus:/consensus
      - ./config:/config

  validator-4:
    container_name: validator-4
    image: "gcr.io/prysmaticlabs/prysm/validator:latest"
    command: ${VALIDATOR_4_ARGS}
    depends_on:
      beacon-chain-4:
        condition: service_started
    volumes:
      - ./consensus:/consensus
      - ./config:/config